FROM n8nio/n8n:latest

ENV DB_TYPE=postgresdb
ENV DB_POSTGRESDB_HOST=postgres.railway.internal
ENV DB_POSTGRESDB_PORT=5432
ENV DB_POSTGRESDB_USER=postgres
ENV DB_POSTGRESDB_PASSWORD=HGJIkXDVQPjwhAXImWVJNZkIxwyyuciS
ENV DB_POSTGRESDB_DATABASE=railway
ENV N8N_PORT=5678

EXPOSE 5678
